name: Request ghmint token
description: Obtain a GitHub App Installation Access Token from ghmint using a GitHub Actions OIDC token

inputs:
  hostname:
    description: Hostname of ghmint
    required: false
    default: sts.yagihash.dev
  scope:
    description: Token scope in <org> or <org>/<repo> format
    required: true
  policy:
    description: Policy name to use
    required: true

outputs:
  token:
    description: GitHub App Installation Access Token obtained from ghmint

runs:
  using: node24
  main: index.js
  post: post.js
