name: "Run Actions Security Check"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  changes:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    outputs:
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: gh auth setup-git
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          filters: |
            workflows:
              - '.github/**'

  ghalint:
    needs: changes
    if: needs.changes.outputs.workflows == 'true'
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      contents: read
      attestations: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install ghalint
        run: |
          # renovate: datasource=github-releases depName=suzuki-shunsuke/ghalint
          version=v1.5.5
          gh release download -R suzuki-shunsuke/ghalint "${version}" -p "ghalint_${version#v}_linux_amd64.tar.gz"
          gh attestation verify "ghalint_${version#v}_linux_amd64.tar.gz" \
            -R suzuki-shunsuke/ghalint \
            --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml
          tar xzf "ghalint_${version#v}_linux_amd64.tar.gz" ghalint
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run ghalint run
        run: ./ghalint run

      - name: Run ghalint act
        run: ./ghalint act

  actionlint:
    needs: changes
    if: needs.changes.outputs.workflows == 'true'
    runs-on: ubuntu-slim
    timeout-minutes: 15
    permissions:
      contents: read
      attestations: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install actionlint
        run: |
          # renovate: datasource=github-releases depName=rhysd/actionlint
          version=v1.7.12
          gh release download -R rhysd/actionlint "${version}" -p "actionlint_${version#v}_linux_amd64.tar.gz"
          gh attestation verify "actionlint_${version#v}_linux_amd64.tar.gz" --repo rhysd/actionlint
          tar xzf "actionlint_${version#v}_linux_amd64.tar.gz" actionlint
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run actionlint
        run: ./actionlint
