name: "Test Action"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run action
        id: ghmint
        uses: ./
        with:
          scope: ${{ github.repository }}
          policy: test

      - name: Verify token works
        env:
          GH_TOKEN: ${{ steps.ghmint.outputs.token }}
        run: gh auth status
